return {
    "apple", "banana", "cat", "dog", "elephant", "flower", "guitar", "house",
    "jacket", "kite", "lion", "mountain", "notebook", "orange", "penguin",
    "queen", "river", "sunflower", "tree", "umbrella", "violin", "whale",
    "xylophone", "yacht", "zebra", "accept", "build", "create", "dance",
    "eat", "fly", "grow", "help", "imagine", "jump", "know", "laugh",
    "make", "notice", "open", "play", "question", "run", "sing", "talk",
    "understand", "visit", "write", "yell", "zoom", "amazing", "beautiful",
    "calm", "delightful", "energetic", "friendly", "gracious", "happy",
    "intelligent", "joyful", "kind", "lively", "magnificent", "noble",
    "optimistic", "peaceful", "quick", "radiant", "strong", "talented",
    "unique", "vibrant", "wise", "youthful", "zealous", "adventure", "bravery",
    "courage", "dream", "energy", "freedom", "grit", "harmony", "imagination",
    "journey", "knowledge", "love", "mystery", "nature", "opportunity",
    "passion", "quest", "respect", "strength", "trust", "unity", "vision",
    "wonder", "youth", "zeal", "airplane", "bicycle", "candle", "dolphin",
    "elephant", "fountain", "giraffe", "helicopter", "igloo", "jungle",
    "kangaroo", "lighthouse", "mushroom", "notebook", "octopus", "piano",
    "quilt", "robot", "sailboat", "telescope", "unicorn", "volcano",
    "waterfall", "xenon", "yarn", "zucchini", "ant", "bear", "caterpillar",
    "deer", "eagle", "falcon", "goat", "hawk", "iguana", "jellyfish",
    "koala", "lemur", "mouse", "newt", "owl", "parrot", "quokka", "rat",
    "snake", "turtle", "urchin", "vulture", "walrus", "xerus", "yak",
    "zebra", "abacus", "balloon", "cactus", "daisy", "eggplant", "fence",
    "grape", "honey", "iceberg", "jigsaw", "kettle", "lollipop", "mango",
    "nectarine", "ocean", "pebble", "quasar", "raccoon", "sponge", "taco",
    "ukulele", "vase", "whistle", "xylophonist", "yogurt", "zest", "actor",
    "baker", "carpenter", "doctor", "engineer", "farmer", "gardener",
    "hairdresser", "inventor", "jeweler", "knitter", "librarian", "musician",
    "nurse", "optician", "painter", "quilter", "researcher", "scientist",
    "teacher", "usher", "veterinarian", "waiter", "x-ray", "yachtsman",
    "zoologist", "abandon", "bargain", "calculate", "decorate", "evaluate",
    "fabricate", "generate", "hesitate", "illustrate", "juggle", "knead",
    "locate", "motivate", "negotiate", "organize", "participate", "question",
    "rejuvenate", "simulate", "transform", "utilize", "validate", "whisper",
    "accelerate", "believe", "contemplate", "discover", "examine", "fascinate",
    "gather", "hasten", "inspire", "justify", "kindle", "leverage", "manifest",
    "navigate", "observe", "perceive", "quench", "act"
}